[[plugins]]
repo = 'Shougo/deoppet.nvim'
on_event = 'InsertEnter'
hook_source = '''
	imap <C-k>  <Plug>(deoppet_expand)
	imap <expr><Tab>  deoppet#expandable() ?
	\ "\<Plug>(deoppet_expand)" : "\<Tab>"
	imap <C-f>  <Plug>(deoppet_jump_forward)
	imap <C-b>  <Plug>(deoppet_jump_backward)
	xmap <C-l>  <Plug>(deoppet_select_text)
	xmap <C-x>  <Plug>(deoppet_cut_text)

  call deoppet#initialize()
	call deoppet#custom#option('snippets_dirs',
  \ [expand('~/.vim/ultisnips')] +
	\ globpath(&runtimepath, 'neosnippets', 1, 1))

'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
