#!/bin/bash

DOTFILES_PATH="${HOME}/.ghq/github.com/0ta2/dotfiles"
DOTFILES_GITHUB="https://github.com/0ta2/dotfiles.git"


print_error() {
    printf "\033[31m    [×] $1\033[m\n"
}

print_success() {
    printf "\033[32m    [✓] $1\033[m\n"
}

print_warning() {
    printf "\033[33m    [!] $1\033[m\n"
}

print_title() {
    printf "\n\n\033[35m$1\033[m\n\n"
}

print_message() {
    printf "    $1\n"
}


is_exists() {
  which "$1" >/dev/null 2>&1
  return $?
}

DOTFILES_LOGO='
  ██████╗  ██████╗ ████████╗███████╗██╗██╗     ███████╗███████╗
  ██╔══██╗██╔═══██╗╚══██╔══╝██╔════╝██║██║     ██╔════╝██╔════╝
  ██║  ██║██║   ██║   ██║   █████╗  ██║██║     █████╗  ███████╗
  ██║  ██║██║   ██║   ██║   ██╔══╝  ██║██║     ██╔══╝  ╚════██║
  ██████╔╝╚██████╔╝   ██║   ██║     ██║███████╗███████╗███████║
  ╚═════╝  ╚═════╝    ╚═╝   ╚═╝     ╚═╝╚══════╝╚══════╝╚══════╝
  =============================================================
  1. Download https://github.com/0ta2/dotfiles.git
  2. Symlinking dot files to your home directory

  Copyright (c) 2016 0ta2
  Licensed under the MIT license.
'

# dotfiles download
download_dotfiles() {
  print_title "Download dotfiles"
  if [ -d ${DOTFILES_PATH} ]; then
    print_warning "Already exists"
    exit 1
  else
    if is_exists "git"; then
      print_message "Git clone dotfiles..."
      mkdir -p `dirname ${DOTFILES_PATH}`
      git clone --recursive -q ${DOTFILES_GITHUB} ${DOTFILES_PATH}
      print_success "Successfully downloaded"
    else
      print_message "Downloading dotfiles..."
      curl -sL https://github.com/0ta2/dotfiles/archive/master.zip | tar xz
      mv dotfiles-master dotfiles
      print_success "Successfully downloaded"
    fi
  fi
}

# dotfiles deploy
deploy_dotfiles() {
  if [ -d ${DOTFILES_PATH} ]; then
    cd ${DOTFILES_PATH}

    make deploy

     if [ $? == 0 ]; then
       print_success "Sccessfully deploy"
     else
       print_error "Unsuccessfully deploy"
     fi  
  fi

    print_error "${DOTFILES_PATH}: Not found"

}

# dotfiles initialize
dotfiles_initialize() {
  print_title "Initializing dotfiles"

  if [ -e Makefile ]; then
    make init
  else
    print_error "Makefile Not found"
  fi
}

# Main
main() {
  # print logo
  echo "${DOTFILES_LOGO}"
  
  print_message "xcode-select --install を実行します。"
  
  xcode-select --install >/dev/null 2>&1
  while :
  do
    xcode-select -p >/dev/null 2>&1
    if [ $? == 0 ]; then
      exit 0
    fi
    sleep 30
  done

  # download dotfiles
  # priority git -> curl
  download_dotfiles

  # make deploy to create symlink
  # create symlink
  deploy_dotfiles

  # execute shell files
  dotfiles_initialize
}

main
